import { useEffect, useState } from "react";
import axios from "axios";
import {
  RadialBarChart,
  RadialBar,
  Legend,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import { LanguageIcon } from "@heroicons/react/24/outline";
import { ADMIN_URL } from "../../utils/api";

// Picked slightly different colors from the CV one for distinction
const COLORS = ["#60A5FA", "#F472B6", "#34D399", "#F59E0B", "#8B5CF6"];

const ClGeneratedCard = () => {
  const [clData, setClData] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const token = sessionStorage.getItem("token");
        const response = await axios.get(
          `${ADMIN_URL}/analytics/cl-lang/count`,
          {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        );
        setClData(response.data);
      } catch (error) {
        console.error("Error fetching CL generation data:", error);
      }
    };

    fetchData();
  }, []);

  if (!clData) {
    return (
      <div className="bg-white rounded-xl shadow-md p-6 w-full">
        <p className="text-gray-500">Loading CL Generation Stats...</p>
      </div>
    );
  }

  const chartData = Object.entries(clData.cl_generated_by).map(
    ([language, data], index) => ({
      name: language,
      value: data.generated,
      percent: data.percent,
      fill: COLORS[index % COLORS.length],
    })
  );

  return (
    <div className="rounded-xl shadow-md p-6 w-full h-64 bg-white">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-base font-bold mb-2">CLs Generated by Language</h3>
          <p className="text-sm text-gray-500">
            Total Users: {clData.total_users}
          </p>
        </div>
        <LanguageIcon className="h-8 w-8 text-pink-500" />
      </div>

      <div className="h-[74%] -mt-4">
        <ResponsiveContainer width="100%" height="100%">
          <RadialBarChart
            cx="50%"
            cy="50%"
            innerRadius="20%"
            outerRadius="90%"
            barSize={15}
            data={chartData}
          >
            <RadialBar
              minAngle={15}
              label={{ position: "insideStart", fill: "#fff", fontSize: 11 }}
              background
              clockWise
              dataKey="value"
            />
            <Tooltip
              formatter={(value, name, props) => {
                const percent = props?.payload?.percent ?? 0;
                return [`${value} CLs (${percent}%)`, name];
              }}
              labelFormatter={() => ""}
            />
            <Legend
              iconSize={10}
              layout="horizontal"
              verticalAlign="bottom"
              align="center"
            />
          </RadialBarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
};

export default ClGeneratedCard;
